[platformio]
default_envs = sender, receiver

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_flags =
    -DBRAKE32_UNIT_ID=1

[env:sender]                    ; Beetle ESP32-C3 — engine bay/cabin box
board = dfrobot_beetle_esp32c3
board_build.partitions = huge_app.csv
build_src_filter = +<common/> +<sender/>
lib_deps =
    adafruit/Adafruit MCP9600 Library
    adafruit/Adafruit BusIO

[env:receiver]
board = esp32-c6-devkitc-1
board_build.partitions = huge_app.csv
build_src_filter = +<common/> +<receiver/>
lib_deps =
    lovyan03/LovyanGFX
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1